import gql from "graphql-tag"

export const GET_LIST = gql`
    query {
        data{
            taskList{
                id,
                title,
                subTaskList,
                performedList
            },
        count
        }
    }
`